### ISSUE TITLE
Deploy To Org doesn't work as test class misses meta xml file

### ISSUE THREAD

**Issue by rsoesemann** [codefriar/promise#1]
<img width="756" alt="bildschirmfoto 2018-01-15 um 19 09 58" src="https://user-images.githubusercontent.com/8180281/34956068-c13d6f72-fa27-11e7-8f44-d75b4e70427a.png">

**Comment by codefriar** [comment]
The demo_ classes are intentionally missing their .xml files as they're NOT to be deployed to production. Only the Promise.cls need to be deployed.

**Comment by rsoesemann** [comment]
But the deployment fails completely. There are not Promise.cls files in my org.

**Comment by codefriar** [comment]
Thats right. Manually install the promise.cls

**Comment by rsoesemann** [comment]
Will do. I guess you should remove the button then...
